header:
  license:
    spdx-id: EPL-2.0
    copyright-owner: Contributors to the Eclipse Foundation.
    content: |
      This program and the accompanying materials are made available under the terms of the
      Eclipse Public License v2.0 which accompanies this distribution, and is available at
      http://www.eclipse.org/legal/epl-v20.html

    pattern: |
      This program and the accompanying materials are made available under the terms of the
      Eclipse Public License v2.0 which accompanies this distribution, and is available at
      http://www.eclipse.org/legal/epl-v20.html

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/package-info.java'
    - '**/packageinfo'
    - '**/module-info.java'
    - '**/*.bnd'
    - '**/*.bndrun'
    - '**/*.xml'
    - '**/*.ecore'
    - '**/*.genmodel'
    - '**/*.md'
    - '**/*.MD'
    - '**/.keep'
    - '**/*.jetproperties'
    - '**/*.javajet'
    - '**/*.javajetinc'
    - '**/*.properties'
    - '**/*.maven'
    - '**/*.html'
    - '**/*.ftl'
    - '**/*.aird'
    - '**/*.basic'
    - '**/.classpath'
    - 'LICENSE'
    - CONTRIBUTING
    - 'NOTICE'
    - 'Jenkinsfile'
    - '.gitattributes'
    - '.github/**'
    - '.gitignore'
    - 'cnf/release/**.*'
    - '.gradle-wrapper/gradle-wrapper.properties'
    - '.licenserc.yaml'
    - '**/.project'
    - '**/*.prefs'
    - mvnw
    - mvnw.cmd
    - license.template

 
  comment: always
